default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: myuser
  password: mypassword
  host: db

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
