default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
